# generated by datamodel-codegen:
#   filename:  openapi.json

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, SecretStr, conint, constr


class AgentListItem(BaseModel):
    id: str = Field(..., description='Unique ID of the agent.', title='Id')
    name: str = Field(..., description='Display name for the agent.', title='Name')
    created_at: datetime = Field(
        ..., description='When the agent was created.', title='Created At'
    )
    updated_at: datetime = Field(
        ..., description='When the agent was last updated.', title='Updated At'
    )


class BuiltinToolResponse(BaseModel):
    name: str = Field(
        ...,
        description='Name identifying the built-in tool. Pass this exact value as `tools[].name` to attach the tool to an agent.',
        title='Name',
    )
    description: str = Field(
        ...,
        description='What the tool does and when the agent should call it.',
        title='Description',
    )
    parameters: dict[str, Any] = Field(
        ...,
        description="Raw JSON Schema object describing the tool's parameters.",
        title='Parameters',
    )
    execution_mode: str = Field(
        ...,
        description='How the agent behaves while the tool runs: `interactive` speaks the result back to the caller, `hold` executes silently.',
        title='Execution Mode',
    )


class CallDirection(Enum):
    inbound = 'inbound'
    outbound = 'outbound'


class CallStatus(Enum):
    dialing = 'dialing'
    active = 'active'
    ended = 'ended'
    failed = 'failed'
    refused = 'refused'


class CreateCallRequest(BaseModel):
    from_number: str = Field(
        ...,
        description='Number to place the call from, in E.164 format. Must be registered to the account and have an agent assigned; that agent handles the call.',
        examples=['+14155550132'],
        title='From Number',
    )
    to_number: str = Field(
        ...,
        description='Destination phone number, in E.164 format.',
        examples=['+12125550148'],
        title='To Number',
    )


class DeliveryStatus(Enum):
    pending = 'pending'
    delivered = 'delivered'
    failed = 'failed'


class DtmfCollectionProfile(BaseModel):
    parameter_name: str = Field(
        ...,
        description="Name of the tool parameter collected from the caller's telephone keypad instead of from speech.",
        examples=['card_number'],
        title='Parameter Name',
    )
    min_digits: conint(ge=1, le=64) = Field(
        ...,
        description='Fewest digits accepted before the entry counts as complete.',
        examples=[15],
        title='Min Digits',
    )
    max_digits: conint(ge=1, le=64) = Field(
        ...,
        description='Most digits accepted before collection stops.',
        examples=[16],
        title='Max Digits',
    )
    sensitive: bool | None = Field(
        None,
        description='Whether the collected value is a secret. `true` suppresses every spoken and stored trace of the value; `false` allows normal read-back.',
        examples=[True],
        title='Sensitive',
    )
    terminator: str | None = Field(None, description='Key that ends entry early. Defaults to `#`.', examples=['#'], title='Terminator')
    confirm: bool | None = Field(
        None,
        description='Read the entry back for keypad confirmation before using it.',
        examples=[True],
        title='Confirm',
    )
    timeout_seconds: conint(ge=1, le=300) | None = Field(
        None,
        description='Seconds of keypad silence before the entry is abandoned.',
        examples=[20],
        title='Timeout Seconds',
    )
    escalate_hotkey_disabled: bool | None = Field(
        None,
        description='Disable the `*` key that hands the caller to a human.',
        examples=[False],
        title='Escalate Hotkey Disabled',
    )
    prompt: str = Field(
        ...,
        description='Spoken to the caller when keypad entry starts.',
        examples=['Using your keypad, enter your card number, then press pound.'],
        title='Prompt',
    )


class ErrorItem(BaseModel):
    message: str = Field(..., title='Message')
    param: str | None = Field(None, title='Param')


class ErrorResponse(BaseModel):
    code: str = Field(..., title='Code')
    message: str = Field(..., title='Message')
    param: str | None = Field(None, title='Param')
    request_id: str = Field(..., title='Request Id')
    errors: list[ErrorItem] | None = Field(None, title='Errors')
    detail: Any | None = Field(None, deprecated=True, title='Detail')


class HttpMethod(Enum):
    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'


class HttpToolHeader(BaseModel):
    name: str = Field(
        ..., description='Header name sent with every tool call.', title='Name'
    )
    last_set_at: datetime = Field(
        ...,
        description="When this header was last set. Equals the agent's `updated_at`: headers are written together whenever the tool list is replaced.",
        title='Last Set At',
    )


class HttpToolHeaderInput(BaseModel):
    name: str = Field(
        ...,
        description='Header name, e.g. `Authorization`.',
        examples=['Authorization'],
        title='Name',
    )
    value: str | None = Field(
        None,
        description='Header value to set or rotate. Omit to keep the stored value unchanged (the read side never returns values).',
        examples=['Bearer st_live_abc123'],
        title='Value',
    )
    remove: bool | None = Field(
        False,
        description='Set to delete this header from the stored tool.',
        title='Remove',
    )


class ImportPhoneNumberRequest(BaseModel):
    phone_number: str = Field(
        ...,
        description='Customer-owned phone number to import, in E.164 format.',
        examples=['+14155550132'],
        title='Phone Number',
    )
    termination_uri: str | None = Field(
        None,
        description='FQDN of the carrier SIP trunk that terminates outbound calls for this number, optionally as a `sip:` URI with a transport parameter.',
        examples=['my-trunk.pstn.twilio.com'],
        title='Termination Uri',
    )


class LlmConfigRequest(BaseModel):
    base_url: str = Field(
        ...,
        description='HTTPS base URL of the OpenAI-compatible endpoint.',
        examples=['https://api.openai.com/v1'],
        title='Base Url',
    )
    model: str = Field(
        ...,
        description='Model name sent in the chat-completions request body.',
        examples=['gpt-4o-mini'],
        title='Model',
    )
    api_key: str = Field(
        ...,
        description='API key for the endpoint. Write-only; never returned.',
        title='Api Key',
    )


class LlmConfigResponse(BaseModel):
    base_url: str = Field(
        ...,
        description='HTTPS base URL of the OpenAI-compatible endpoint.',
        title='Base Url',
    )
    model: str = Field(
        ..., description='Model name used for the conversational LLM.', title='Model'
    )


class PhoneNumberAssignAgentRequest(BaseModel):
    agent_id: str = Field(
        ...,
        description='ID of the agent that should answer calls to this number.',
        examples=['agent_b4c9e0d27a314c6e9f5a8d2e6c1b0a47'],
        title='Agent Id',
    )


class Type(Enum):
    managed = 'managed'
    imported = 'imported'


class PhoneNumberResponse(BaseModel):
    id: str = Field(
        ..., description='Unique ID of the phone number record.', title='Id'
    )
    phone_number: str = Field(
        ..., description='The number, in E.164 format.', title='Phone Number'
    )
    agent_id: str | None = Field(
        ...,
        description='Agent that answers calls to this number. Null when no agent is assigned.',
        title='Agent Id',
    )
    type: Type = Field(
        ...,
        description='`managed` numbers are purchased through AssemblyAI; `imported` numbers are customer-owned and route via their own SIP trunk.',
        title='Type',
    )
    termination_uri: str | None = Field(
        ...,
        description='FQDN of the carrier SIP trunk for imported numbers. Null for managed numbers.',
        title='Termination Uri',
    )
    country_code: str | None = Field(
        None,
        description='ISO 3166-1 alpha-2 country of the number, when known.',
        title='Country Code',
    )
    number_type: str | None = Field(
        None,
        description='Number class reported by the provider, e.g. `local`.',
        title='Number Type',
    )
    label: str | None = Field(
        None, description='Free-form label stored with the number.', title='Label'
    )
    created_at: datetime = Field(
        ..., description='When the number was registered.', title='Created At'
    )
    updated_at: datetime = Field(
        ..., description='When the number was last updated.', title='Updated At'
    )


class PlaintextHttpToolConfig(BaseModel):
    url: str = Field(
        ...,
        description='HTTPS endpoint to call when the tool is invoked.',
        examples=['https://example.com/orders/status'],
        title='Url',
    )
    http_method: HttpMethod | None = Field(
        'POST', description='HTTP method used when calling the endpoint.'
    )
    headers: list[HttpToolHeaderInput] | None = Field(
        None,
        description='HTTP headers sent with every tool call, e.g. for authentication. Each entry sets/rotates a header (with `value`), keeps the stored value (name only), or removes it (`remove: true`). Write-only: values are stored encrypted and never returned.',
        examples=[[{'name': 'Authorization', 'value': 'Bearer st_live_abc123'}]],
        title='Headers',
    )


class ExecutionMode(Enum):
    interactive = 'interactive'
    hold = 'hold'


class PreConnectReturn(BaseModel):
    name: str = Field(
        ...,
        description="Name this value is captured under. Referenced by a later request's `sends` and by the fields `allow_overrides` permits.",
        examples=['customer_tier'],
        title='Name',
    )
    path: str = Field(
        ...,
        description='Dotted path into the JSON response body, e.g. `customer.tier` or `results.0.id`. Shape is validated at write time; whether the path exists is only knowable at call time.',
        examples=['customer.tier'],
        title='Path',
    )
    default: str | None = Field(
        None,
        description='Used when the path does not resolve. Without one, an unresolved path leaves the value unset.',
        examples=['standard'],
        title='Default',
    )


class PreConnectReturnResponse(BaseModel):
    name: str = Field(
        ..., description='Name this value is captured under.', title='Name'
    )
    path: str = Field(
        ..., description='Dotted path into the JSON response body.', title='Path'
    )
    default: str | None = Field(
        None, description='Used when the path does not resolve.', title='Default'
    )


class NumberType(Enum):
    local = 'local'
    mobile = 'mobile'
    national = 'national'


class PurchaseAvailablePhoneNumberRequest(BaseModel):
    country_code: str = Field(
        ...,
        description='Two-letter ISO 3166-1 alpha-2 country code to search in.',
        examples=['US'],
        title='Country Code',
    )
    number_type: NumberType = Field(
        ...,
        description='Kind of number to search for.',
        examples=['local'],
        title='Number Type',
    )
    area_code: int | None = Field(
        None,
        description='Restrict the search to this area code.',
        examples=[415],
        title='Area Code',
    )
    locality: str | None = Field(
        None,
        description='Restrict the search to this city or locality.',
        examples=['San Francisco'],
        title='Locality',
    )
    label: str | None = Field(
        None,
        description='Free-form label stored with the purchased number.',
        examples=['Support line'],
        title='Label',
    )
    agent_id: str | None = Field(
        None,
        description='Agent to assign to the number immediately after purchase.',
        examples=['agent_b4c9e0d27a314c6e9f5a8d2e6c1b0a47'],
        title='Agent Id',
    )


class PurchasePhoneNumberRequest(BaseModel):
    phone_number: str = Field(
        ...,
        description='Specific phone number to purchase, in E.164 format.',
        examples=['+14155550132'],
        title='Phone Number',
    )


class ResponseInstructions(BaseModel):
    success: constr(max_length=500) | None = Field(
        None,
        description="Appended to the agent's spoken-reply guidance when the tool completes successfully. Plain static text, up to 500 characters; no runtime substitution. A completed call whose response body contains an error message still counts as successful.",
        examples=['Mention that availability comes from the live inventory system and may change.'],
        title='Success',
    )
    error: constr(max_length=500) | None = Field(
        None,
        description="Appended to the agent's spoken-reply guidance when the tool fails. Plain static text, up to 500 characters; no runtime substitution.",
        examples=['Do not suggest trying again; offer to connect the caller with a human agent.'],
        title='Error',
    )


class ResponseMetadata(BaseModel):
    next_cursor: str | None = Field(
        '',
        description='Cursor for the next page; pass it back as the `cursor` query parameter. Empty string when there are no further results.',
        title='Next Cursor',
    )


class SessionArtifact(BaseModel):
    type: str = Field(
        ...,
        description='Artifact kind: one of `audio`, `timeline`, or `metadata`.',
        title='Type',
    )
    url: str = Field(
        ...,
        description='Pre-signed download URL. Expires after a short TTL; re-fetch the session for a fresh link.',
        title='Url',
    )
    content_type: str = Field(
        ..., description='MIME type of the artifact.', title='Content Type'
    )


class SessionListItem(BaseModel):
    id: str = Field(..., description='Unique ID of the session.', title='Id')
    agent_id: str | None = Field(
        None,
        description='Agent the session ran with. Null when no agent was used.',
        title='Agent Id',
    )
    status: str = Field(
        ...,
        description='Lifecycle status of the session, e.g. `completed`.',
        title='Status',
    )
    public_close_reason: str | None = Field(
        None,
        description='Why the session ended, when known.',
        title='Public Close Reason',
    )
    duration_seconds: float | None = Field(
        None,
        description='Session length in seconds. Null while the session is active.',
        title='Duration Seconds',
    )
    created_at: datetime | None = Field(
        None, description='When the session was created.', title='Created At'
    )
    ended_at: datetime | None = Field(
        None,
        description='When the session ended. Null while the session is active.',
        title='Ended At',
    )


class SessionListResponse(BaseModel):
    sessions: list[SessionListItem] = Field(
        ..., description='Page of sessions, newest first.', title='Sessions'
    )
    has_more: bool | None = Field(
        False,
        description='True when more results may be available; fetch the next page with `response_metadata.next_cursor`.',
        title='Has More',
    )
    response_metadata: ResponseMetadata | None = Field(
        {'next_cursor': ''},
        description='Pagination details for fetching the next page.',
        validate_default=True,
    )


class SessionResponse(BaseModel):
    id: str = Field(..., description='Unique ID of the session.', title='Id')
    agent_id: str | None = Field(
        None,
        description='Agent the session ran with. Null when no agent was used.',
        title='Agent Id',
    )
    status: str = Field(
        ...,
        description='Lifecycle status of the session, e.g. `completed`.',
        title='Status',
    )
    public_close_reason: str | None = Field(
        None,
        description='Why the session ended, when known.',
        title='Public Close Reason',
    )
    duration_seconds: float | None = Field(
        None,
        description='Session length in seconds. Null while the session is active.',
        title='Duration Seconds',
    )
    config: dict[str, Any] | None = Field(
        None,
        description='Session configuration captured when the session started.',
        title='Config',
    )
    created_at: datetime | None = Field(
        None, description='When the session was created.', title='Created At'
    )
    ended_at: datetime | None = Field(
        None,
        description='When the session ended. Null while the session is active.',
        title='Ended At',
    )
    artifacts: list[SessionArtifact] | None = Field(
        [],
        description='Recordings and transcripts produced by the session. Empty until the session completes.',
        title='Artifacts',
        validate_default=True,
    )


class TargetKind(Enum):
    human = 'human'
    agent = 'agent'


class TokenCreateRequest(BaseModel):
    expires_in_seconds: conint(ge=1, le=600) | None = Field(
        60,
        description='Seconds the token stays valid for connecting. Short by design — the token rides in the WebSocket URL, so a leaked one expires fast. Defaults to 60.',
        title='Expires In Seconds',
    )


class TokenResponse(BaseModel):
    token: str = Field(
        ...,
        description='Short-lived credential to pass on the realtime WebSocket handshake as `?token=`. Authenticates the account and project only; never the raw API key.',
        title='Token',
    )
    expires_at: datetime = Field(
        ...,
        description='When the token stops being accepted on connect (UTC). This is the connect window, not the session length: once a session is established it runs to completion regardless of this time.',
        title='Expires At',
    )


class TransferMode(Enum):
    cold = 'cold'
    warm = 'warm'


class TransferTarget(BaseModel):
    name: str = Field(..., title='Name')
    kind: TargetKind
    phone_number: str | None = Field(None, title='Phone Number')
    agent_id: str | None = Field(None, title='Agent Id')
    mode: TransferMode | None = 'cold'
    consult_instructions: str | None = Field(None, title='Consult Instructions')
    ring_timeout_seconds: int | None = Field(None, title='Ring Timeout Seconds')
    consult_timeout_seconds: int | None = Field(None, title='Consult Timeout Seconds')
    record_consult: bool | None = Field(None, title='Record Consult')


class TransferTargetResponse(BaseModel):
    name: str = Field(
        ..., description='Name the agent uses to reference this target.', title='Name'
    )
    kind: str = Field(
        ...,
        description='`human` to dial a phone number, `agent` to hand off to another agent.',
        title='Kind',
    )
    phone_number: str | None = Field(
        None,
        description='E.164 number dialed for a human target.',
        title='Phone Number',
    )
    agent_id: str | None = Field(
        None,
        description='ID of the agent handed off to for an agent target.',
        title='Agent Id',
    )
    mode: str = Field(
        ...,
        description='`cold` transfers immediately, `warm` consults before connecting.',
        title='Mode',
    )
    consult_instructions: str | None = Field(
        None,
        description='Instructions spoken to the warm-transfer destination before connecting.',
        title='Consult Instructions',
    )
    ring_timeout_seconds: int | None = Field(
        None,
        description='Seconds to wait for the target to answer before giving up.',
        title='Ring Timeout Seconds',
    )
    consult_timeout_seconds: int | None = Field(
        None,
        description='Seconds to wait during a warm-transfer consult before connecting.',
        title='Consult Timeout Seconds',
    )
    record_consult: bool | None = Field(
        None,
        description='Record the warm-transfer consult leg (audio only). Default off.',
        title='Record Consult',
    )


class VoiceConfig(BaseModel):
    voice_id: str = Field(
        ...,
        description='AssemblyAI voice name, e.g. `ivy`, `james`, or `mia`.',
        examples=['ivy'],
        title='Voice Id',
    )


class WebhookDeliveryResponse(BaseModel):
    id: str = Field(..., description='Unique ID of the delivery.', title='Id')
    subscription_id: str = Field(
        ...,
        description='Subscription this delivery belongs to.',
        title='Subscription Id',
    )
    session_id: str = Field(
        ...,
        description='Session whose event triggered the delivery.',
        title='Session Id',
    )
    attempt_count: int = Field(
        ...,
        description='Number of delivery attempts made so far.',
        title='Attempt Count',
    )
    status: DeliveryStatus = Field(..., description='Current delivery state.')
    http_status_code: int | None = Field(
        None,
        description='HTTP status returned by the endpoint on the most recent attempt. Null when no response was received.',
        title='Http Status Code',
    )
    error: str | None = Field(
        None,
        description='Why the most recent attempt failed. Null on success.',
        title='Error',
    )
    delivered_at: datetime | None = Field(
        None,
        description='When the delivery succeeded. Null until then.',
        title='Delivered At',
    )
    next_retry_at: datetime | None = Field(
        None,
        description='When the next retry is scheduled. Null when none is pending.',
        title='Next Retry At',
    )
    created_at: datetime = Field(
        ..., description='When the delivery was first enqueued.', title='Created At'
    )


class WebhookEvent(Enum):
    session_started = 'session.started'
    session_completed = 'session.completed'
    call_connected = 'call.connected'
    call_ended = 'call.ended'
    call_failed = 'call.failed'


class WebhookSubscriptionResponse(BaseModel):
    id: str = Field(..., description='Unique ID of the subscription.', title='Id')
    agent_id: str | None = Field(
        None,
        description='Agent this subscription is scoped to. Null when it covers every agent on the account.',
        title='Agent Id',
    )
    url: str = Field(
        ..., description='Endpoint event deliveries are POSTed to.', title='Url'
    )
    events: list[WebhookEvent] = Field(
        ..., description='Event types this subscription receives.', title='Events'
    )
    enabled: bool = Field(
        ..., description='Whether deliveries are currently active.', title='Enabled'
    )
    secret_version: int = Field(
        ...,
        description='Increments each time the signing secret is rotated.',
        title='Secret Version',
    )
    created_at: datetime = Field(
        ..., description='When the subscription was created.', title='Created At'
    )
    updated_at: datetime = Field(
        ..., description='When the subscription was last updated.', title='Updated At'
    )


class AgentListResponse(BaseModel):
    agents: list[AgentListItem] = Field(
        ..., description='Page of agents, newest first.', title='Agents'
    )
    has_more: bool | None = Field(
        False,
        description='True when more results may be available; fetch the next page with `response_metadata.next_cursor`.',
        title='Has More',
    )
    response_metadata: ResponseMetadata | None = Field(
        {'next_cursor': ''},
        description='Pagination details for fetching the next page.',
        validate_default=True,
    )


class BuiltinToolListResponse(BaseModel):
    builtin_tools: list[BuiltinToolResponse] = Field(
        ..., description='Built-in tools available to agents.', title='Builtin Tools'
    )


class CallGetResponse(BaseModel):
    id: str = Field(..., description='Unique ID of the call.', title='Id')
    status: CallStatus = Field(..., description='Current lifecycle state of the call.')
    direction: CallDirection = Field(
        ..., description='Whether the call was received (inbound) or placed (outbound).'
    )
    agent_id: str = Field(
        ..., description='Agent that handled the call.', title='Agent Id'
    )
    from_number: str = Field(
        ..., description='Caller phone number, in E.164 format.', title='From Number'
    )
    to_number: str = Field(
        ..., description='Destination phone number, in E.164 format.', title='To Number'
    )
    session_id: str = Field(
        ...,
        description='Session created for this call; use it to fetch artifacts.',
        title='Session Id',
    )
    ended_at: datetime | None = Field(
        None,
        description='When the call ended. Null while the call is in progress.',
        title='Ended At',
    )
    duration_seconds: float | None = Field(
        None,
        description='Call length in seconds. Null while the call is in progress.',
        title='Duration Seconds',
    )
    created_at: datetime = Field(
        ..., description='When the call was created.', title='Created At'
    )
    updated_at: datetime = Field(
        ..., description='When the call was last updated.', title='Updated At'
    )


class CallListItem(BaseModel):
    id: str = Field(..., description='Unique ID of the call.', title='Id')
    status: CallStatus = Field(..., description='Current lifecycle state of the call.')
    direction: CallDirection = Field(
        ..., description='Whether the call was received (inbound) or placed (outbound).'
    )
    agent_id: str = Field(
        ..., description='Agent that handled the call.', title='Agent Id'
    )
    from_number: str = Field(
        ..., description='Caller phone number, in E.164 format.', title='From Number'
    )
    to_number: str = Field(
        ..., description='Destination phone number, in E.164 format.', title='To Number'
    )
    session_id: str = Field(
        ...,
        description='Session created for this call; use it to fetch artifacts.',
        title='Session Id',
    )
    ended_at: datetime | None = Field(
        None,
        description='When the call ended. Null while the call is in progress.',
        title='Ended At',
    )
    duration_seconds: float | None = Field(
        None,
        description='Call length in seconds. Null while the call is in progress.',
        title='Duration Seconds',
    )
    created_at: datetime = Field(
        ..., description='When the call was created.', title='Created At'
    )
    updated_at: datetime = Field(
        ..., description='When the call was last updated.', title='Updated At'
    )


class CallListResponse(BaseModel):
    calls: list[CallListItem] = Field(
        ..., description='Page of calls, newest first.', title='Calls'
    )
    has_more: bool | None = Field(
        False,
        description='True when more results may be available; fetch the next page with `response_metadata.next_cursor`.',
        title='Has More',
    )
    response_metadata: ResponseMetadata | None = Field(
        {'next_cursor': ''},
        description='Pagination details for fetching the next page.',
        validate_default=True,
    )


class CallResponse(BaseModel):
    id: str = Field(..., description='Unique ID of the call.', title='Id')
    status: CallStatus = Field(..., description='Current lifecycle state of the call.')


class CreateWebhookSubscriptionRequest(BaseModel):
    url: constr(max_length=2048) = Field(
        ...,
        description='HTTPS endpoint that receives event deliveries via POST.',
        examples=['https://example.com/webhooks/voice-agents'],
        title='Url',
    )
    events: list[WebhookEvent] = Field(
        ...,
        description='Event types to deliver. Must be non-empty and contain no duplicates.',
        examples=[['session.completed', 'call.ended']],
        title='Events',
    )
    secret: SecretStr = Field(
        ...,
        description='HMAC-SHA256 signing secret, at least 32 characters. Each delivery carries an `X-AAI-Signature` header computed with it. Never returned by the API.',
        examples=['k7Jq2vXw9zR4tY6uB1nM3cP8sD5fG0hL2aE9oI4xZQw'],
        title='Secret',
    )
    agent_id: str | None = Field(
        None,
        description='Limit the subscription to events from this agent. Omit to receive events for every agent on the account.',
        examples=['agent_b4c9e0d27a314c6e9f5a8d2e6c1b0a47'],
        title='Agent Id',
    )
    enabled: bool | None = Field(
        True,
        description='Whether the subscription starts active. Disabled subscriptions receive no deliveries.',
        title='Enabled',
    )


class HttpToolConfigResponse(BaseModel):
    url: str = Field(
        ..., description='HTTPS endpoint called when the tool is invoked.', title='Url'
    )
    http_method: HttpMethod = Field(
        ..., description='HTTP method used when calling the endpoint.'
    )
    headers: list[HttpToolHeader] = Field(
        ...,
        description='Names of the headers sent with every tool call. Header values are write-only and never returned; send the name back with no value to keep the stored secret.',
        title='Headers',
    )


class PhoneNumberListResponse(BaseModel):
    phone_numbers: list[PhoneNumberResponse] = Field(
        ..., description='Page of phone numbers, newest first.', title='Phone Numbers'
    )
    has_more: bool | None = Field(
        False,
        description='True when more results may be available; fetch the next page with `response_metadata.next_cursor`.',
        title='Has More',
    )
    response_metadata: ResponseMetadata | None = Field(
        {'next_cursor': ''},
        description='Pagination details for fetching the next page.',
        validate_default=True,
    )


class PlaintextPreConnectRequest(BaseModel):
    http: PlaintextHttpToolConfig = Field(
        ..., description='HTTPS endpoint called before the conversation starts.'
    )
    sends: list[str] | None = Field(
        None,
        description="Names captured by an earlier entry's `returns`, sent to this endpoint. Entries run in order, so only an earlier entry's names are resolvable.",
        examples=[['customer_tier']],
        title='Sends',
    )
    returns: list[PreConnectReturn] | None = Field(
        None,
        description="Values captured from this endpoint's JSON response body.",
        title='Returns',
    )
    timeout_ms: int | None = Field(
        None,
        description="Lowers this request's timeout. Each request has its own 800 ms ceiling; this can only shorten the wait, never extend it.",
        examples=[250],
        title='Timeout Ms',
    )
    allow_overrides: list[str] | None = Field(
        None,
        description="Agent fields this request's captured values may replace. Closed vocabulary; today only `greeting`.",
        examples=[['greeting']],
        title='Allow Overrides',
    )


class PlaintextToolDefinition(BaseModel):
    id: str | None = Field(
        None,
        description="Server-assigned ID for the tool. Returned on reads and ignored on writes: the server assigns it when the tool is first created and keeps it for as long as the tool's `name` is unchanged.",
        examples=['tool_d8f6c1a43e9b4d7aa2c56b0e9d4f8a29'],
        title='Id',
    )
    name: str = Field(
        ...,
        description='Name the agent uses to call the tool.',
        examples=['get_order_status'],
        title='Name',
    )
    description: str | None = Field(
        None,
        description='What the tool does and when the agent should call it. Required unless `name` references an AssemblyAI platform tool, whose definition is server-owned.',
        examples=["Look up the status of a customer's order by order number."],
        title='Description',
    )
    http: PlaintextHttpToolConfig | None = Field(
        None,
        description='HTTP endpoint the server calls when the tool is invoked. Omit for tools executed client-side over the WebSocket connection.',
    )
    parameters: dict[str, Any] | None = Field(
        None,
        description='Raw JSON Schema object describing the tool\'s parameters, e.g. {"type": "object", "properties": {...}, "required": [...]}.',
        examples=[{'properties': {'order_number': {'description': "The customer's order number.", 'type': 'string'}}, 'required': ['order_number'], 'type': 'object'}],
        title='Parameters',
    )
    timeout_seconds: conint(ge=1, le=300) | None = Field(
        120,
        description='Maximum seconds to wait for the tool to complete, between 1 and 300.',
        examples=[30],
        title='Timeout Seconds',
    )
    execution_mode: ExecutionMode | None = Field(
        'interactive',
        description='How the agent behaves while the tool runs: `interactive` speaks the result back to the caller, `hold` executes silently.',
        title='Execution Mode',
    )
    response_instructions: ResponseInstructions | None = Field(
        None,
        description="Shapes what the agent says after this tool resolves: the matching text is appended to the agent's built-in spoken-reply guidance, after the tool result, so it is the last instruction the model reads. Applies only when the agent speaks a reply for the result — no reply follows a committed cold call transfer, and calls rejected before execution (duplicates, invalid arguments, repeated failures) use fixed recovery wording.",
    )
    dtmf_collected_arguments: list[DtmfCollectionProfile] | None = Field(
        None,
        description='Parameters the caller enters on the telephone keypad rather than speaking, each naming one property of `parameters`. Telephone calls only: a WebSocket session receives no keypad input.',
        title='Dtmf Collected Arguments',
    )


class PreConnectRequestResponse(BaseModel):
    http: HttpToolConfigResponse = Field(
        ..., description='HTTPS endpoint called before the conversation starts.'
    )
    sends: list[str] | None = Field(
        None,
        description='Names captured by an earlier request and sent to this one.',
        title='Sends',
    )
    returns: list[PreConnectReturnResponse] | None = Field(
        None,
        description="Values captured from this endpoint's JSON response body.",
        title='Returns',
    )
    timeout_ms: int | None = Field(
        None,
        description='Lowered timeout for this request. Null means the full 800 ms ceiling applies.',
        title='Timeout Ms',
    )
    allow_overrides: list[str] | None = Field(
        None,
        description="Agent fields this request's captured values may replace.",
        title='Allow Overrides',
    )


class ToolResponse(BaseModel):
    id: str = Field(..., description='Unique ID for the tool.', title='Id')
    name: str = Field(
        ..., description='Name the agent uses to call the tool.', title='Name'
    )
    description: str | None = Field(
        None,
        description='What the tool does and when the agent should call it. Null for platform tools, whose definition is server-owned and not stored.',
        title='Description',
    )
    http: HttpToolConfigResponse | None = Field(
        None,
        description='HTTP endpoint the server calls when the tool is invoked. Null for tools executed client-side over the WebSocket connection.',
    )
    parameters: dict[str, Any] | None = Field(
        None,
        description="Raw JSON Schema object describing the tool's parameters.",
        title='Parameters',
    )
    timeout_seconds: int = Field(
        ...,
        description='Maximum seconds to wait for the tool to complete.',
        title='Timeout Seconds',
    )
    execution_mode: str = Field(
        ...,
        description='How the agent behaves while the tool runs: `interactive` speaks the result back to the caller, `hold` executes silently.',
        title='Execution Mode',
    )
    response_instructions: ResponseInstructions | None = Field(
        None,
        description="Spoken-reply shaping configured for this tool: `success` / `error` text appended to the agent's delivery guidance after the tool resolves.",
    )
    dtmf_collected_arguments: list[DtmfCollectionProfile] | None = Field(
        None,
        description='Tool arguments the caller enters on the phone keypad instead of speaking them. Telephony calls only. Send the list back unchanged on update to keep the stored configuration.',
        title='Dtmf Collected Arguments',
    )


class UpdateWebhookSubscriptionRequest(BaseModel):
    url: constr(max_length=2048) | None = Field(
        None,
        description='New HTTPS endpoint for deliveries.',
        examples=['https://example.com/webhooks/voice-agents'],
        title='Url',
    )
    events: list[WebhookEvent] | None = Field(
        None,
        description='Replacement list of event types. Must be non-empty and contain no duplicates.',
        examples=[['session.completed']],
        title='Events',
    )
    secret: SecretStr | None = Field(
        None,
        description='New HMAC-SHA256 signing secret, at least 32 characters. Rotating it increments `secret_version`.',
        title='Secret',
    )
    enabled: bool | None = Field(
        None,
        description='Enable or disable deliveries for this subscription.',
        title='Enabled',
    )


class WebhookDeliveryListResponse(BaseModel):
    deliveries: list[WebhookDeliveryResponse] | None = Field(
        None, description='Page of deliveries, newest first.', title='Deliveries'
    )
    has_more: bool | None = Field(
        False,
        description='True when more results may be available; fetch the next page with `response_metadata.next_cursor`.',
        title='Has More',
    )
    response_metadata: ResponseMetadata | None = Field(
        {'next_cursor': ''},
        description='Pagination details for fetching the next page.',
        validate_default=True,
    )


class WebhookSubscriptionListResponse(BaseModel):
    subscriptions: list[WebhookSubscriptionResponse] | None = Field(
        None, description='Page of subscriptions, newest first.', title='Subscriptions'
    )
    has_more: bool | None = Field(
        False,
        description='True when more results may be available; fetch the next page with `response_metadata.next_cursor`.',
        title='Has More',
    )
    response_metadata: ResponseMetadata | None = Field(
        {'next_cursor': ''},
        description='Pagination details for fetching the next page.',
        validate_default=True,
    )


class AgentCreateRequest(BaseModel):
    name: str = Field(
        ...,
        description='Display name for the agent.',
        examples=['Customer support agent'],
        title='Name',
    )
    system_prompt: str = Field(
        ...,
        description="System prompt defining the agent's persona, knowledge, and conversation rules.",
        examples=['You are a friendly support agent for Acme Inc. Help customers with orders and shipping questions.'],
        title='System Prompt',
    )
    greeting: str | None = Field(
        None,
        description='Opening line the agent speaks when a conversation starts.',
        examples=['Hi, thanks for calling Acme! How can I help today?'],
        title='Greeting',
    )
    voice: VoiceConfig = Field(..., description='Voice the agent speaks with.')
    input: dict[str, Any] | None = Field(
        None,
        description='Input configuration: audio format, turn detection, and key terms. Defaults to 24kHz PCM audio.',
        title='Input',
    )
    output: dict[str, Any] | None = Field(
        None,
        description='Output configuration: audio format and volume. Defaults to 24kHz PCM audio.',
        title='Output',
    )
    tools: list[PlaintextToolDefinition] | None = Field(
        None,
        description='Tools the agent can call during a conversation.',
        title='Tools',
    )
    pre_connect_requests: list[PlaintextPreConnectRequest] | None = Field(
        None,
        description='HTTP requests made before the conversation starts, run in order. Each captures values from its JSON response that later requests can send on and that may fill the fields named in `allow_overrides`. At most 2.',
        title='Pre Connect Requests',
    )
    transfer_targets: list[TransferTarget] | None = Field(
        None,
        description='Destinations a live call may be transferred to.',
        title='Transfer Targets',
    )
    outbound_trunk_id: str | None = Field(
        None,
        description='SIP trunk used to dial out for human transfers and outbound calls. Required when a human transfer target is configured.',
        title='Outbound Trunk Id',
    )
    caller_id: str | None = Field(
        None,
        description='E.164 number presented as the caller ID on outbound dials.',
        title='Caller Id',
    )
    llm: list[LlmConfigRequest] | None = Field(
        None,
        description='Conversational LLM for the agent. A single entry overrides the default model; the list is capped at one in v1.',
        title='Llm',
    )


class AgentResponse(BaseModel):
    id: str = Field(..., description='Unique ID of the agent.', title='Id')
    name: str = Field(..., description='Display name for the agent.', title='Name')
    system_prompt: str = Field(
        ...,
        description="System prompt defining the agent's persona, knowledge, and conversation rules.",
        title='System Prompt',
    )
    greeting: str | None = Field(
        None,
        description='Opening line the agent speaks when a conversation starts.',
        title='Greeting',
    )
    tools: list[ToolResponse] | None = Field(
        None,
        description='Tools the agent can call during a conversation.',
        title='Tools',
    )
    pre_connect_requests: list[PreConnectRequestResponse] | None = Field(
        None,
        description='HTTP requests made before the conversation starts, in the order they run. Header values are write-only and never returned.',
        title='Pre Connect Requests',
    )
    voice: VoiceConfig = Field(..., description='Voice the agent speaks with.')
    input: dict[str, Any] = Field(
        ...,
        description='Input configuration: audio format, turn detection, and key terms.',
        title='Input',
    )
    output: dict[str, Any] = Field(
        ...,
        description='Output configuration: audio format and volume.',
        title='Output',
    )
    transfer_targets: list[TransferTargetResponse] | None = Field(
        None,
        description='Destinations a live call may be transferred to.',
        title='Transfer Targets',
    )
    outbound_trunk_id: str | None = Field(
        None,
        description='SIP trunk used to dial out for human transfers and outbound calls.',
        title='Outbound Trunk Id',
    )
    caller_id: str | None = Field(
        None,
        description='E.164 number presented as the caller ID on outbound dials.',
        title='Caller Id',
    )
    llm: list[LlmConfigResponse] | None = Field(
        None,
        description='Conversational LLM configured for the agent. The api_key is write-only and never returned.',
        title='Llm',
    )
    created_at: datetime = Field(
        ..., description='When the agent was created.', title='Created At'
    )
    updated_at: datetime = Field(
        ..., description='When the agent was last updated.', title='Updated At'
    )


class AgentUpdateRequest(BaseModel):
    name: str | None = Field(
        None,
        description='New display name for the agent.',
        examples=['Customer support agent'],
        title='Name',
    )
    system_prompt: str | None = Field(
        None,
        description="New system prompt defining the agent's persona, knowledge, and conversation rules.",
        examples=['You are a friendly support agent for Acme Inc. Help customers with orders, shipping, and returns.'],
        title='System Prompt',
    )
    greeting: str | None = Field(
        None,
        description='New opening line the agent speaks when a conversation starts.',
        examples=['Hi, thanks for calling Acme! How can I help today?'],
        title='Greeting',
    )
    voice: VoiceConfig | None = Field(None, description='New voice for the agent.')
    input: dict[str, Any] | None = Field(
        None,
        description='New input configuration: audio format, turn detection, and key terms.',
        title='Input',
    )
    output: dict[str, Any] | None = Field(
        None,
        description='New output configuration: audio format and volume.',
        title='Output',
    )
    tools: list[PlaintextToolDefinition] | None = Field(
        None,
        description='Replaces the stored tool list; omit to keep existing tools. Per header, send `value` to set/rotate, the name alone to keep the stored secret, or `remove: true` to delete it.',
        title='Tools',
    )
    pre_connect_requests: list[PlaintextPreConnectRequest] | None = Field(
        None,
        description='Replaces the stored pre-connect request list; omit to keep the existing one. Entries have no name, so header secrets are kept by LIST POSITION: reordering the list reorders the stored secrets with it. Per header, send `value` to set/rotate, the name alone to keep the stored secret, or `remove: true` to delete it.',
        title='Pre Connect Requests',
    )
    transfer_targets: list[TransferTarget] | None = Field(
        None,
        description='Replaces the stored transfer-target list; omit to keep existing targets.',
        title='Transfer Targets',
    )
    outbound_trunk_id: str | None = Field(
        None,
        description='SIP trunk used to dial out for human transfers and outbound calls. Required when a human transfer target is configured.',
        title='Outbound Trunk Id',
    )
    caller_id: str | None = Field(
        None,
        description='E.164 number presented as the caller ID on outbound dials.',
        title='Caller Id',
    )
    llm: list[LlmConfigRequest] | None = Field(
        None,
        description='Replaces the stored LLM config; omit to keep the existing config.',
        title='Llm',
    )
