# generated by datamodel-codegen:
#   filename:  ws_wrapped.json

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Type(Enum):
    audio = 'audio'


class Encoding(Enum):
    audio_pcm = 'audio/pcm'


class SampleRate(Enum):
    int_24000 = 24000


class AudioPCM(BaseModel):
    encoding: Literal['audio/pcm']
    sample_rate: SampleRate | None = 24000


class Encoding1(Enum):
    audio_pcma = 'audio/pcma'


class AudioPCMA(BaseModel):
    encoding: Literal['audio/pcma']


class Encoding2(Enum):
    audio_pcmu = 'audio/pcmu'


class AudioPCMU(BaseModel):
    encoding: Literal['audio/pcmu']


class Role(Enum):
    system = 'system'
    user = 'user'


class Type2(Enum):
    conversation_message = 'conversation.message'


class ConversationMessage(BaseModel):
    content: str
    role: Role
    type: Type2


class HttpToolConfig(BaseModel):
    headers_ciphertext: str | None = ''
    headers_encrypted_data_key: str | None = ''
    headers_kms_key_id: str | None = ''
    method: str | None = 'POST'
    url: str


class Type3(Enum):
    input_audio = 'input.audio'


class InputAudio(BaseModel):
    audio: str
    type: Type3


class Type4(Enum):
    input_speech_started = 'input.speech.started'


class InputSpeechStarted(BaseModel):
    timestamp: float | None = None
    type: Type4 | None = 'input.speech.started'


class Type5(Enum):
    input_speech_stopped = 'input.speech.stopped'


class InputSpeechStopped(BaseModel):
    timestamp: float | None = None
    type: Type5 | None = 'input.speech.stopped'


class LlmWireConfig(BaseModel):
    api_key_ciphertext: str | None = ''
    api_key_encrypted_data_key: str | None = ''
    api_key_kms_key_id: str | None = ''
    base_url: str
    model: str


class PreConnectReturnWire(BaseModel):
    default: str | None = None
    name: str
    path: str


class Type6(Enum):
    reply_audio = 'reply.audio'


class ReplyAudio(BaseModel):
    data: str
    reply_id: str
    timestamp: float | None = None
    type: Type6 | None = 'reply.audio'


class Type7(Enum):
    reply_cancel = 'reply.cancel'


class ReplyCancel(BaseModel):
    reply_id: str
    type: Type7


class Type8(Enum):
    reply_create = 'reply.create'


class ReplyCreate(BaseModel):
    instructions: str | None = None
    type: Type8


class Status(Enum):
    completed = 'completed'
    interrupted = 'interrupted'


class Type9(Enum):
    reply_done = 'reply.done'


class ReplyDone(BaseModel):
    reply_id: str
    status: Status
    timestamp: float | None = None
    type: Type9 | None = 'reply.done'


class Type10(Enum):
    reply_started = 'reply.started'


class ReplyStarted(BaseModel):
    item_id: str
    reply_id: str
    timestamp: float | None = None
    type: Type10 | None = 'reply.started'


class Type11(Enum):
    session_end = 'session.end'


class SessionEnd(BaseModel):
    type: Type11


class Type12(Enum):
    session_ended = 'session.ended'


class SessionEnded(BaseModel):
    audio_duration_seconds: float | None = None
    session_duration_seconds: float
    timestamp: float | None = None
    type: Type12 | None = 'session.ended'


class Code(Enum):
    agent_id_not_first = 'agent_id_not_first'
    agent_not_found = 'agent_not_found'
    at_capacity = 'at_capacity'
    audio_rate_violation = 'audio_rate_violation'
    concurrency_exceeded = 'concurrency_exceeded'
    immutable_field = 'immutable_field'
    internal_error = 'internal_error'
    invalid_audio = 'invalid_audio'
    invalid_config = 'invalid_config'
    invalid_format = 'invalid_format'
    invalid_value = 'invalid_value'
    invalid_webhook = 'invalid_webhook'
    session_expired = 'session_expired'
    session_forbidden = 'session_forbidden'
    session_not_found = 'session_not_found'
    unauthorized = 'unauthorized'


class Type13(Enum):
    session_error = 'session.error'


class SessionError(BaseModel):
    code: Code
    message: str
    param: str | None = None
    session_id: str | None = None
    timestamp: float | None = None
    type: Type13 | None = 'session.error'


class Type14(Enum):
    session_ready = 'session.ready'


class Type15(Enum):
    session_resume = 'session.resume'


class SessionResume(BaseModel):
    session_id: str
    type: Type15


class Type16(Enum):
    session_update = 'session.update'


class Type17(Enum):
    session_updated = 'session.updated'


class Type18(Enum):
    text = 'text'


class TextInput(BaseModel):
    type: Literal['text']


class TextOutput(BaseModel):
    type: Literal['text']


class ExecutionMode(Enum):
    hold = 'hold'
    interactive = 'interactive'


class Type20(Enum):
    function = 'function'


class Type21(Enum):
    tool_call = 'tool.call'


class ToolCall(BaseModel):
    arguments: Any
    call_id: str
    name: str
    timestamp: float | None = None
    type: Type21 | None = 'tool.call'


class Type22(Enum):
    object = 'object'


class ToolParameters(BaseModel):
    properties: dict[str, Any] | None = {}
    required: list[str] | None = []
    type: Type22 | None = 'object'


class ToolResponseInstructions(BaseModel):
    error: str | None = None
    success: str | None = None


class Type23(Enum):
    tool_result = 'tool.result'


class ToolResult(BaseModel):
    call_id: str
    is_error: bool | None = False
    result: str
    type: Type23


class Type24(Enum):
    transcript_agent = 'transcript.agent'


class TranscriptAgent(BaseModel):
    interrupted: bool
    item_id: str
    reply_id: str
    text: str
    timestamp: float | None = None
    type: Type24 | None = 'transcript.agent'


class Type25(Enum):
    transcript_agent_delta = 'transcript.agent.delta'


class TranscriptAgentDelta(BaseModel):
    delta: str
    end_ms: int | None
    item_id: str
    reply_id: str
    start_ms: int | None
    timestamp: float | None = None
    type: Type25 | None = 'transcript.agent.delta'


class Type26(Enum):
    transcript_user = 'transcript.user'


class TranscriptUser(BaseModel):
    item_id: str
    text: str
    timestamp: float | None = None
    type: Type26 | None = 'transcript.user'


class Type27(Enum):
    transcript_user_delta = 'transcript.user.delta'


class TranscriptUserDelta(BaseModel):
    item_id: str
    text: str
    timestamp: float | None = None
    type: Type27 | None = 'transcript.user.delta'


class Type28(Enum):
    semantic_vad = 'semantic_vad'
    server_vad = 'server_vad'


class TurnDetectionConfig(BaseModel):
    interrupt_response: bool | None = True
    interruption_delay: int | None = None
    max_silence: int | None = 3000
    min_silence: int | None = 1000
    type: Type28 | None = None
    vad_threshold: float | None = 0.5


class WebhookConfigInline(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    events: list[str]
    secret: str | None = None
    url: str


class AudioInput(BaseModel):
    continuous_partials: bool | None = None
    format: AudioPCM | AudioPCMU | AudioPCMA | None = Field(
        None, discriminator='encoding'
    )
    keyterms: list[str] | None = None
    language_codes: list[str] | None = None
    transcription_mode: str | None = None
    transcription_prompt: str | None = None
    turn_detection: TurnDetectionConfig | None = None
    type: Literal['audio']
    voice_focus: str | None = None
    voice_focus_threshold: float | None = None


class AudioOutput(BaseModel):
    format: AudioPCM | AudioPCMU | AudioPCMA | None = Field(
        None, discriminator='encoding'
    )
    type: Literal['audio']
    voice: str
    volume: float | None = None


class PreConnectRequestWire(BaseModel):
    allow_overrides: list[str] | None = []
    http: HttpToolConfig
    returns: list[PreConnectReturnWire] | None = Field([], validate_default=True)
    sends: list[str] | None = []
    timeout_ms: int | None = None


class SessionUpdatePayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str | None = None
    greeting: str | None = None
    input: dict[str, Any] | None = None
    llm: list[dict[str, Any]] | None = None
    output: dict[str, Any] | None = None
    pre_connect_requests: list[dict[str, Any]] | None = None
    system_prompt: str | None = None
    tools: list[dict[str, Any]] | None = None
    webhook: WebhookConfigInline | None = None


class Tool(BaseModel):
    description: str | None = ''
    execution_mode: ExecutionMode | None = 'interactive'
    http: HttpToolConfig | None = None
    name: str
    parameters: ToolParameters | None = None
    response_instructions: ToolResponseInstructions | None = None
    timeout_seconds: float | None = 120.0
    type: Type20


class SessionConfig(BaseModel):
    greeting: str | None = None
    id: str | None = ''
    input: AudioInput | TextInput | None = Field(None, discriminator='type')
    llm: list[LlmWireConfig] | None = Field([], validate_default=True)
    output: AudioOutput | TextOutput | None = Field(None, discriminator='type')
    pre_connect_requests: list[PreConnectRequestWire] | None = Field(
        [], validate_default=True
    )
    system_prompt: str | None = ''
    tools: list[Tool] | None = Field([], validate_default=True)


class SessionReady(BaseModel):
    config: SessionConfig
    expires_at: int
    resume_token: str | None = ''
    session_id: str
    timestamp: float | None = None
    type: Type14 | None = 'session.ready'


class SessionUpdate(BaseModel):
    session: SessionUpdatePayload | None = None
    type: Type16


class SessionUpdatedEvent(BaseModel):
    config: SessionConfig
    timestamp: float | None = None
    type: Type17 | None = 'session.updated'
